config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  root to: 'themes#index'

  resources :themes, only: [:index]

  resources :upvotes, only: [:create]

  resources :comments, only: [:create, :index]

  resources :user_themes, only: [:destroy]

end

app/views/shared/_article.html.erb
  <div class="article-card" data-article-id=<%= article.id %>>
    <div href=<%=article.url  %> class="card-up" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.35)), url(<%= article.img_url %>);">
      <%= link_to article.url , class: "article-card-link'=" do %>
        <h4><%= article.title %></h4>
      <% end %>


      <%= link_to upvotes_path(article_id: article.id), method: :post, class: "card-upvotes #{ "upvoted" if article.upvoted?(current_user)}", remote: :true do%>
         <span><%= article.upvotes.count %></span>  <i class="fas fa-heart"></i>
      <% end %>
    </div>

    <div class="card-down">
      <div class="card-content">
        <div class="card-theme-container">
          <% article.themes.each do |theme| %>
            <div class="user-theme-card"><%= theme.name %></div>
          <% end %>
        </div>
      </div>
      <div class="card-comments-section">
        <div class="comment-form"><input data-article-id=<%= article.id %> class= "comment-input" type="" name="" placeholder="Enter your comment">
        </div>
        <%= link_to "#{pluralize(article.comments.count, "comment")}" ,  "#", class: "comments-list"  %>
      </div>
    <div class="show-comments">
    </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_interests.html.erb
<div class="theme-card-container">

  <% if user_themes.any? %>
    <% user_themes.each do |user_theme| %>
      <div class="user-theme-card">
        <span><%= user_theme.theme.name.capitalize %></span>
        <%= link_to user_theme_path(user_theme), method: :delete do %>
          <i class="far fa-minus-square"></i>
        <% end %>
      </div>
    <% end %>
  <% else %>
    <p>No interests selected yet!</p>
  <% end %>
</div>

app/views/shared/_meetup.html.erb
  <div class="meetup-card">
    <a href=<%=meetup.url  %> class="card-up" style="background-image: linear-gradient(rgba(0,0,0,0.2),rgba(0,0,0,0.35)), url('https://www.billboard.com/files/styles/article_main_image/public/media/eventbrite-NEW-logo-2018-billboard-1548.jpg');">
      <h4><%= meetup.title%></h4>
    </a>
    <div class="card-down-meetup">
      <div class="card-time-section">
         <%= meetup.date_time.strftime("Le %d/%m/%Y") %>
      </div>
    </div>
  </div>


<!-- t.strftime("Printed on %m/%d/%Y")   #=> "Printed on 11/19/2007"
t.strftime("at %I:%M%p") -->

app/views/shared/_navbar.html.erb
<nav>
  <h1>Dev News</h1>

    <div class="nav-right">
      <% if user_signed_in? %>
        <button class="navbar-hamburger" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <i class="fas fa-bars"></i>
       </button>

        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuButton">
          <%= link_to "Log out", destroy_user_session_path, method: :delete,
          class: "dropdown-item" %>
        </div>

      <% else %>
        <%= link_to "Login", new_user_session_path, class: "nav-link", id: "login" %>
      <% end %>

    </div>
</nav>